### ISSUE TITLE
To do list for hackathon

### ISSUE THREAD

**Issue by raysinensis** [rnabioco/clustifyr#198]
package building:
- [x] fix the logo
- [x] rename to `clustifyr` (so it's `clustifyr::clustifyr()`)
- [x] remove s_small and s_small3, so no package errors are thrown in building, but that means removing tests as well
- [x] evaluate vignette chunks (to identify errors) <- mostly unreferenced packages and data files, currently set as eval = F
- [x] currently all RMD examples need clustifyrdata, is that ok or do we need to subset to 2 clusters?
- [x] dplyr variables throwing warnings in building
- [x] does this install and run on windows?
- [ ] **put on bioconductor**

good code practice:
- [x] code tidying by packages
- [x] no "print()"
- [x] all T/F update to TRUE/FALSE
- [x] no if (abc == TRUE)
- [x] add usage examples to all functions?
- [x] clusters in seurat 3 meta now come as factors, which throws a lot of warnings
- [x] unify var/option order and names
- [X] opinions on the state of the tutorial website
- [x] tutorial example of going from ucsc data (like https://cells.ucsc.edu/?ds=cortex-dev#, there's also annotated markers at https://github.com/cole-trapnell-lab/garnett/issues/4), and Ebi SCE atlas (https://www.ebi.ac.uk/gxa/sc/experiments/E-EHCA-2/downloads, also need metadata)
- [x] clustifyrdata cleaning and documenting, also needs to be renamed now, also too large now?

classification theory:
- [ ] what is the best dataset example? pbmcs aren't actually that good (CD8) without correction
- [ ] way to assess whether markers are actually good
- [X] negative selection on markers
- [x] lower limit on fgsea n_perm?

**Comment by jayhesselberth** [comment]
- [ ] All `T/F` updated to `TRUE/FALSE`

**Comment by raysinensis** [comment]
for factor coersion: 1, try `forcats::fct_explicit_na` or `levels(x) <- value`
2, as.character first or just leave as is (but jay is rewriting that part)
