### ISSUE TITLE
Convert use_seurat_comp/meta to S3

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#221]
What is a `comp`? component? expression? I don't think this is a good suffix.

And why is it `use_)`? Couldn't it just be `seurat_expr()` and `seurat_meta()`?

Need to dispatch on v2 and v3.

**Comment by raysinensis** [comment]
does it need to be S3?
checking whether class is Seurat or seurat works too

so rename to seurat_ref (or seurat_avg) and seurat_meta?
