### ISSUE TITLE
Add data files for examples

### ISSUE THREAD

**Issue by agillen** [rnabioco/clustifyr#227]
Need sample files to write examples for at least two functions:

1. `file_marker_parse()` - "file with positive and negative markers, as described in garnett"
2. `gmt_to_list()` - Broad GMT: Gene Matrix Transposed file format (*.gmt)

**Comment by raysinensis** [comment]
currently dumped to data-raw folder

**Comment by agillen** [comment]
Thanks. Moved both files to inst/extdata in the examples2 branch and added examples for both relevant functions.

@raysinensis - the `file_marker_parse()` function fails on hsPBMC_markers.txt. Haven't looked into why yet...

**Comment by raysinensis** [comment]
hsPBMC has no negative markers...
I've fixed the code to check
