### ISSUE TITLE
Add UMAP, nCount_RNA, nFeature_RNA, etc. columns to pbmc4_meta data

### ISSUE THREAD

**Issue by sheridar** [rnabioco/clustifyr#241]
Add the UMAP data so it can be used in the vignettes. To include a plot_cols() example in the vignette we need additional meta.data columns.

**Comment by raysinensis** [comment]
I'll try to make a better example

**Comment by kriemo** [comment]
Need to fix in the vignette but found in `pbmc_meta` now.
