### ISSUE TITLE
Errors after stripping seurat attributes

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#249]
I'm seeing errors like this, I assume it's caused by stripping seurat attributes from data files.

``` r
library(clustifyr)

clustify(
  s_small,
  pbmc_bulk_matrix,
  cluster_col = "res.1",
  seurat_out = FALSE,
  per_cell = FALSE
)
#> Error in as.data.frame(seurat_object@dr[[dr2]]@cell.embeddings): trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots
```

<sup>Created on 2019-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by raysinensis** [comment]
That is actually because the default slot to look for is umap, whereas the Seurat objects only have "tsne". Adding dr = "tsne" should resolve errors

**Comment by raysinensis** [comment]
Try with argument dr = "tsne"
The Seurat objects don't have the default umap slot

Tested fine on my laptop, but maybe there are other issues
