### ISSUE TITLE
New classification paper

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#250]
https://www.biorxiv.org/content/early/2019/05/23/645358.full.pdf

http://scibet.cancer-pku.cn/

**Comment by raysinensis** [comment]
started looking at the benchmarking

with sensible defaults, scmap should not be that bad for cases of no reference (and I have tested clustifyr, which basically does what scmap does, to work fine)

also clustifyr will take bulk RNA seq and microarray, which the competition (aside from singleR does not)
