### ISSUE TITLE
Error: 'by' can't contain join column 'classified' which is missing from LHS

### ISSUE THREAD

**Issue by PedroRaposo** [rnabioco/clustifyr#254]
Hello,

I created a clustify object (based on a Seurat object), and then I tried to plot by using the plot_best_call() function:

```
> res = clustify(input = GetAssayData(Seurat_Object_1), cluster_col = "orig.ident", ref_mat = as.matrix(GetAssayData(Seurat_Object_2)), seurat_out = T, dr = "umap", metadata = Seurat_Object_1@meta.data)

>plot_best_call(res, Seurat_Object_1, "classified")
Error: 'by' can't contain join column 'classified' which is missing from LHS
```

It seems there's something with joining the column classified, and I cannot find what it is. Has someone encountered this error before?

Thank you

**Comment by raysinensis** [comment]
Hi,
the `cluster_col` argument in both `clustify` and `plot_best_call` asks for the column in your metadata with cluster numbers, by default it would be "seurat_clusters" or something like "RNA_snn_res.0.8".

`clustify` also can take both a matrix as input, or a Seurat object straight-up, which changes the other arguments required. If a matrix is used for input, output is a correlation matrix (`seurat_out` is disabled) that goes into `plot_best_call`. However if a Seurat object is used directly as input, the identity assignments are already inserted into the output Seurat object in the "type" column.

May I suggest trying something like:
```
ref = seurat_ref(Seurat_Object_2, # the object to use as reference
                 cluster_col = "seurat_clusters" # change to whatever column in Seurat_Object_2 metadata that contains the cell type names you want
)

res = clustify(input = Seurat_Object_1, # directly give the function the Seurat object
               cluster_col = "seurat_clusters",  # change to whatever column in Seurat_Object_1 metadata that contains the cluster info you want
               ref_mat = ref, 
               seurat_out = T, 
               dr = "umap"
)

DimPlot(res, group.by = "type")
```

And if you want to use a matrix as input:
```
ref = seurat_ref(Seurat_Object_2,
                 cluster_col = "seurat_clusters"
)

res <- clustify(input = GetAssayData(Seurat_Object_1),
                metadata = Seurat_Object_1@meta.data,
                cluster_col = "seurat_clusters",
                ref_mat = ref,
                dr = "umap",
                query_genes = Seurat_Object_1@assays$RNA@var.features # we find using variable features instead of all genes improves accuracy, note that if a seurat object is used for input, this is done under the hood
)

plot_best_call(res, 
               seurat_meta(Seurat_Object_1),  # the function finds umap coordinates
               "seurat_clusters" # this should be the same as cluster_col you used in clustify
) 
```
Hopefully this helps.

**Comment by PedroRaposo** [comment]
@raysinensis Thank you so much for your assistance.

Using both methods, when running the clustify function I got the following error:

> Error in cor(as.matrix(query_mat), ref_mat, method  = compute_method):
>     'x' must be numeric

My Seurat object never gave me problems about variable types using Seurat. I used here the `cluster_col` variable as the numeric column `seurat_clusters`, and still gave mt this error.
Is something wrong with me object?

**Comment by raysinensis** [comment]
The most common case where I see that error is if the function arguments fail to point to the clustering information, such as the if cluster_col given doesn't actually exist in the metadata...

If you are sure that is not the issue, would you mind uploading a subset of your object so I can take a look?

**Comment by PedroRaposo** [comment]
I'll gladly send you part of the data. I'm going to be absent a couple of weeks. I'll send you when I come back. Thank you very much

**Comment by PedroRaposo** [comment]
Hello again @raysinensis!
I have subset the two Seurat objects that I want to use.
It seems they are too big (80 Mb - sorry, I cannot reduced the data further) to be sent by the GitHub comments. Is there any other way to send them?
Thank you.

**Comment by raysinensis** [comment]
@PedroRaposo 
can you upload to google drive or dropbox and share a link?

**Comment by PedroRaposo** [comment]
@raysinensis 
Here it is: https://www.dropbox.com/sh/bh30ev0phbcy7uj/AAAFtuNReGWBDsCcEDkIj3CRa?dl=0
Thank you in advance!

**Comment by raysinensis** [comment]
@PedroRaposo 
Hi, I think I identified the issue. The function looks for var.genes in `seurat_object@assays$RNA@var.features`, it should default to using all genes instead of none (we do recommend manually feeding in a vector of variable genes via `query_genes` argument if possible). This is fixed in the latest version. Please reinstall and try again.

**Comment by PedroRaposo** [comment]
@raysinensis, you're absolutely right.
Thank you!
