### ISSUE TITLE
Support for SingleCellExperiment objects?

### ISSUE THREAD

**Issue by LTLA** [rnabioco/clustifyr#294]
If your plan is to submit to BioC, it would be great to have support for _SingleCellExperiment_ objects. I am trying to increase the diversity of cell type annotation methods in Bioconductor (_SingleR_, etc.), and it seems that this package would be a good fit.

We took _SingleR_ through a similar refactoring process (see LTLA/SingleR#1), which considerably improved its performance and reference availability. Possibly worth considering some of the points here, especially the use of ExperimentHub to hold your datasets.

**Comment by raysinensis** [comment]
Thanks for the suggestion. We had internally talked about support for SCE, and now it's (roughly) done.

We have been watching your work on `SingleR` closely. The discussions and improvements made to it have been very helpful for us in thinking about our own package development.
