### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by PedroRaposo** [rnabioco/clustifyr#302]
Hi RNAbioco team,

There is a general concern comparing scRNA and bulk RNA data, because of their very different nature (either on different laboratory protocols, different normalizations, etc). I have tried clustifyR and it works fine for me - I can compare the two types of data, successfully. However, this software operates as a black box for me, and so I was wondering if there is any paper associated with clustifyR, to clarify some ideas.

Thank you

**Comment by raysinensis** [comment]
Hi, thank you for your interest. We have finally put out a preprint, here:
https://www.biorxiv.org/content/early/2019/11/26/855064.full.pdf

In short, it is doing ranked correlation on cluster average expression. For general use, it works decently.

Please let us know if you have other comments and suggestions.
