### ISSUE TITLE
Rproj file?

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#339]
Did the clustifyr.Rproj file disappear? I can't open it as a project.

**Comment by kriemo** [comment]
It was removed due to a bioconductor requirement:

>The raw package directory should not contain unnecessary files, system files, or hidden files such as .DS_Store, .project, .git, cache file, log files, .Rproj, .so, etc.. These files may be present in your local directory but should not be commited to git (see .gitignore).>

https://bioconductor.org/developers/package-guidelines/

**Comment by jayhesselberth** [comment]
OK, I'll get by with creating one locally.
