### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#345]
- download and crop image from unsplash (https://unsplash.com/photos/3HYA5mEPRsE)
- upload to hexmake (https://connect.thinkr.fr/hexmake/)
- invert image in hexmake

Here's a draft:
![hex-clustifyr](https://user-images.githubusercontent.com/355367/78144442-d9192000-73ec-11ea-91d8-34a3dbc3aa93.png)

**Comment by raysinensis** [comment]
Is there a way to crop the image keeping just the part inside the hexagon? I'm not seeing it...
