### ISSUE TITLE
Visualization to compare between classifications

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyr#353]
In rnabioco/antigen-tracking#6 we found two groups who did a similar experiment and ended up with different naming conventions for the same / similar cell types.

It would be nice to have a way to compare the classifications to understand the relationship between labels in the two sets.

We could generate a matrix/heatmap with the two classifications as rownames and colnames, with calculated correlation values between each pair plotted in each cell. This should visualize both cases where there are clear, 1-to-1 associations, and cases where a classification in one study is comprised of multiple classifications from another. I would suggest combining the expression in each cell type in each classification set, and calculating correlations between those "meta" classifications.
 
cc @sheridar

**Comment by jayhesselberth** [comment]
Or maybe a PCA plot with labels?

**Comment by sheridar** [comment]
I like the PCA idea, here's an example of a heatmap: https://github.com/rnabioco/antigen-tracking/commit/5d2251b922a497dd25af85d0df3fc9e047edcfaf

**Comment by jayhesselberth** [comment]
I think the heatmap would be a bit easier to read if all the "1"s were e.g. rows and all the "2"s were columns.
