### ISSUE TITLE
seurat_ref(): Error when building reference matrix from Seurat object (group length is 0 but data length >0)

### ISSUE THREAD

**Issue by federicaress** [rnabioco/clustifyr#366]
Hi!
I encountered a problem: when I try to build a reference matrix from a Seurat object. 
If I write:
`myrefmatrix = seurat_ref ( seurat_object = <mySeuratObject)`
 
the error is:
`error in split.default(colnames(mat), cluster_info_temp): group length is 0 but data length >0`

I tried three different data sets and the error remains the same.

What should I do?
Thank you for your time 

Edit: typo

**Comment by raysinensis** [comment]
Hi, please let us know if you still have issues.
Closing for now.
