### ISSUE TITLE
utility to build references from public cellbrowsers

### ISSUE THREAD

**Issue by kriemo** [rnabioco/clustifyr#368]
This would be really useful and would be pretty straightforward to implement for ucsc cellbrowser and cellxgene. 

For ucsc the meta data and matrix are stored as compressed files that can be downloaded using a standard url scheme. For cellxgene the user would have to point to the URL with the .h5ad file (e.g. links in https://www.kidneycellatlas.org/). 

i.e. psuedocode:
```r
cb_url <- "https://rnabioco.github.io/lung-scrna/?ds=lung_regeneration_lps_model"
ref <- build_reference(cb_url, type = "ucsc", cluster_col = "cell_types")
```

```r
h5_url <- "https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Mature_Immune_v2.1.h5ad"
ref <- build_reference(h5_url, type = "cellxgene", cluster_col = "cell_types")
```

**Comment by raysinensis** [comment]
Probably want a tutorial page on this? And an un-run example of the code in the main README and vignette
