### ISSUE TITLE
clustify_lists - 'pct'

### ISSUE THREAD

**Issue by Dazcam** [rnabioco/clustifyr#386]
I have a set of gene lists that I'm using for cell type classification and have run `clustify_lists()`  as described in your [tutorial](https://rnabioco.github.io/clustifyr/articles/clustifyR.html) in which the metric parameter is set to 'pct'.

I'm struggling to find a thorough explanation of what is being run under the hood when this the 'pct' option is used. All I could find in the paper was:

> clustify_lists will calculate enrichment with a hypergeometric test, marker overlap with the jaccard index, or use the percent of cells expressing marker genes to annotate cell types.

Could you elaborate on the last (pct) part a bit? It's not 100% clear (at least to me) what is going on, particularly with regard to whether you are comparing marker genes across cells or clusters (or both). 

Many thanks.

**Comment by raysinensis** [comment]
Hi,
For each gene, "pct" calculates % of cells in each cluster with detectable expression. This is then summarized for all genes to reach a "score".

**Comment by Dazcam** [comment]
Hi, and thanks for responding. 

That makes sense, but how is that score summarised exactly?

Is it right to assume no formal statistical test is run here? 

And right to assume that it is the summarised gene 'score' that is compared between the test and query datasets? Or to put it another way, all cells in a cluster in the query dataset are assigned the identity of the cluster in the reference with the most similar  'score'.

Many Thanks.

**Comment by raysinensis** [comment]
for instance, if reference type A has 3 marker genes, and in cluster 1 the detection percentages are 0, 0.1, 0.5, the default is just to take mean, so 0.2 is the "score" for cluster 1.

yes, no statistical testing, more for exploration
