### ISSUE TITLE
new species

### ISSUE THREAD

**Issue by wangjiawen2013** [rnabioco/clustifyr#390]
Hi,
Can I use clustifyr to annotate cell types of some new species, such as rat which is lack of reference ?

**Comment by kriemo** [comment]
There is no built in support for comparing across species. One approach that you could try is to map the genes in the query and reference to a shared set of orthologues, then use clustifyr to compare the orthologues. Usually for simplicity 1-to-1 orthologues are used. Tables of orthologous genes can be obtained from ensembl.
